version: '3'
services:
     portainer:
         container_name: Portainer
         image: portainer/portainer-ce
         restart: always
         ports:
         - "9000:9000"
         volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer-data:/data

volumes:
    portainer-data: